name: Playwright Tests

on:
  workflow_call:
    secrets:
      username:
        required: false
      password:
        required: false
      chat-webhook:
        required: false
    inputs:
      os:
        required: false
        type: string
      options:
        required: false
        type: string
      notify-on-failure:
        required: false
        type: boolean

jobs:
  playwright:
    name: Run Playwright Tests
    continue-on-error: false
    runs-on: ${{ inputs.os }}
    timeout-minutes: 600
    steps:
    - name: Checkout "${{ github.ref }}"
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - name: Install dependencies
      run: npm ci

    # Caching Playwright from: https://github.com/microsoft/playwright/issues/7249
    - name: Get installed Playwright version
      id: playwright-version
      run: echo "version=$(npm ls @playwright/test | grep @playwright | sed 's/.*@//')" >> $GITHUB_OUTPUT
    - uses: actions/cache@v3
      id: playwright-cache
      with:
        path: '~/.cache/ms-playwright'
        key: '${{ runner.os }}-playwright-deps-${{ steps.playwright-version.outputs.version }}'
        restore-keys: |
          ${{ runner.os }}-playwright-deps-
    - name: Install Playwright's dependencies
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium chrome msedge firefox webkit
    # End of caching

    # Some system dependencies are not cached
    - name: Install Playwright's OS dependencies
      run: npx playwright install-deps

    - name: Run Playwright tests
      env:
        TEST_USERNAME: ${{ secrets.username }}
        TEST_PASSWORD: ${{ secrets.password }}
      run: npx playwright test ${{ inputs.options }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: "playwright-report-${{ inputs.os }}"
        path: playwright-report/
        retention-days: 1
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: "test-results-${{ inputs.os }}"
        path: test-results/
        retention-days: 1

    - name: Increment value
      # main
      uses: yoichiro/gh-action-increment-value@5a51be9d5cac40e1cad794227f9e1766dd8036eb
      with:
        target_file: 'build_number.txt'
        commit_message: 'Automatic build number increment '

    - name: Get the build number
      id: build-version
      run: echo "build_number=$(cat build_number.txt)" >> $GITHUB_OUTPUT

    - name: Release
      # v1
      uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
      if: always()
      with:
        tag_name: ${{ steps.build-version.outputs.build_number }}
        files: |
          results.xml

    - name: Google Chat Notification
      # release/v1
      uses: Co-qn/google-chat-notification@b9227d9daa4638c9782a5bd16c4abb86268127a1
      with:
        name: Operate First E2E Test
        url: ${{ secrets.chat-webhook }}
        status: ${{ job.status }}
      if: failure() && inputs.notify-on-failure
